
name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4
    - run: docker build . -t bghfj/next-js-app
    - run: echo "${{secrets.PASSWORD}}" | docker login -u ${{secrets.USERNAME}}  --password-stdin
    - run: docker push bghfj/next-js-app:latest